name: 🆙 Release file check

on:
  push:
    branches:
      - main

jobs:
  check-release:
    name: Release check
    runs-on: ubuntu-latest

    # TODO: skip if there's no release file

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install autopub and plugins
        run: pip install autopub==1.0.0-alpha.14 PyGithub pdm

      - name: Check release
        run: autopub -p autopub_plugins.github check
        id: check
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        run: autopub -p autopub_plugins.github prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: autopub -p pdm -p autopub_plugins.github build
        if: steps.check.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: autopub -p pdm -p autopub_plugins.github publish
        if: steps.check.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
