name: 🆙 Release file check

on:
  # TODO: change this to pull_request_target once ready
  pull_request:
    types: [synchronize, reopened, opened, ready_for_review]
    branches:
      - main

jobs:
  check-release:
    name: Release check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install autopub and plugins
        run: pip install autopub==1.0.0-alpha.18 PyGithub httpx

      - name: Check release
        run: autopub -p autopub_plugins.github.pr_comment -p autopub_plugins.github.release check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
